/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.abhilash_fees_management_system;

//import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Statement; // Correct import




/**
 *
 * @author abhil
 */
public class Sign_up extends javax.swing.JFrame {

    /**
     * Creates new form Sign_up
     */
    public Sign_up() {
        initComponents();
    }
    int id=0;
     
int getId(){
                  ResultSet rs=null;

    try{
               Class.forName("com.mysql.cj.jdbc.Driver");
               String url="jdbc:mysql://localhost:3306/elearning?zeroDateTimeBehavior=CONVERT_TO_NULL";
               Connection con= DriverManager.getConnection(url,"root","");
               String sql="select max(id) from signup";
               
              Statement st = (Statement) con.createStatement();

 
               rs = st.executeQuery(sql);  
    
    while (rs.next()) {
        id = rs.getInt(1); 
    }
} catch (Exception e) {
    e.printStackTrace();
}

return id;
             

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCnum = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtUname = new javax.swing.JTextField();
        txtCPfield = new javax.swing.JPasswordField();
        txtPfield = new javax.swing.JPasswordField();
        txtdob = new com.toedter.calendar.JDateChooser();
        btnsignin = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        lablepassworderror = new javax.swing.JLabel();
        confirmpassworderror = new javax.swing.JLabel();
        labelcontact = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\2ND SEMESTER\\JAVA TECHNOLOGIES\\REPORT\\icons\\signup.png")); // NOI18N
        jLabel1.setText("Sign up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("First Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Last Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 100, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("UserName");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 100, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Passwoord");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 100, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Confirm Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 150, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("D.O.B.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 100, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Contact no.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 100, -1));

        txtCnum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnumActionPerformed(evt);
            }
        });
        txtCnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCnumKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCnumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCnumKeyTyped(evt);
            }
        });
        getContentPane().add(txtCnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 150, 30));

        txtFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 150, 30));

        txtLname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 150, 30));

        txtUname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 150, 30));

        txtCPfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPfieldActionPerformed(evt);
            }
        });
        getContentPane().add(txtCPfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 150, 30));

        txtPfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPfieldActionPerformed(evt);
            }
        });
        txtPfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPfieldKeyTyped(evt);
            }
        });
        getContentPane().add(txtPfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 150, 30));
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 150, 30));

        btnsignin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsignin.setIcon(new javax.swing.ImageIcon("D:\\2ND SEMESTER\\JAVA TECHNOLOGIES\\REPORT\\project Image\\project Image\\logout.png")); // NOI18N
        btnsignin.setText("Log in");
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 130, 40));

        btnsignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsignup.setIcon(new javax.swing.ImageIcon("D:\\2ND SEMESTER\\JAVA TECHNOLOGIES\\REPORT\\project Image\\project Image\\login1.png")); // NOI18N
        btnsignup.setText("Sing Up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 130, 40));

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon("D:\\2ND SEMESTER\\JAVA TECHNOLOGIES\\REPORT\\project Image\\project Image\\cancel1.png")); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 130, 40));

        lablepassworderror.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lablepassworderror.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lablepassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 160, 20));

        confirmpassworderror.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmpassworderror.setForeground(new java.awt.Color(255, 0, 51));
        confirmpassworderror.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmpassworderrorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmpassworderrorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                confirmpassworderrorKeyTyped(evt);
            }
        });
        getContentPane().add(confirmpassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 276, 160, 20));

        labelcontact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelcontact.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(labelcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnumActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameActionPerformed

    private void txtCPfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPfieldActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
validation();
if(validation()){
    insertData();
}
else{
    JOptionPane.showMessageDialog(this,"validation issue");
}     
    }//GEN-LAST:event_btnsignupActionPerformed

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed
Login l1=new Login()  ;
l1.show();
this.dispose();
    }//GEN-LAST:event_btnsigninActionPerformed

    private void txtPfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPfieldActionPerformed

    private void txtPfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPfieldKeyPressed
            // TODO add your handling code here:
    }//GEN-LAST:event_txtPfieldKeyPressed

    private void txtPfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPfieldKeyReleased
      // TODO add your handling code here:
    }//GEN-LAST:event_txtPfieldKeyReleased

    private void txtPfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPfieldKeyTyped
            // TODO add your handling code here:
    }//GEN-LAST:event_txtPfieldKeyTyped

    private void txtCnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnumKeyPressed
   // TODO add your handling code here:
    }//GEN-LAST:event_txtCnumKeyPressed

    private void txtCnumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnumKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnumKeyReleased

    private void txtCnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnumKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnumKeyTyped

    private void confirmpassworderrorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmpassworderrorKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassworderrorKeyPressed

    private void confirmpassworderrorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmpassworderrorKeyReleased
       // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassworderrorKeyReleased

    private void confirmpassworderrorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmpassworderrorKeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassworderrorKeyTyped

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
  txtFname.setText("");
  txtLname.setText("");
  txtUname.setText("");
  txtPfield.setText("");
  txtCPfield.setText("");
  txtCnum.setText("");
  //txtdob.setDate("");


        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed
       String Fname,Lname,Uname,Password,CPassword;
      // int Cnumber;
       Date dob;
       
       void insertData(){
           try{
               SimpleDateFormat s1 = new SimpleDateFormat("yyyy-MM-dd");
               String dob1= s1.format(dob);
               Class.forName("com.mysql.cj.jdbc.Driver");
               String url="jdbc:mysql://localhost:3306/elearning?zeroDateTimeBehavior=CONVERT_TO_NULL";
               Connection con= DriverManager.getConnection(url,"root","");
              
              String sql = "INSERT INTO signup (Fname, Lname, Uname, Password, dob) VALUES ( ?, ?, ?, ?, ?)";

              PreparedStatement st = con.prepareStatement(sql); // Correct declaration

              
              //st.setInt(1,getId());
              st.setString(1,Fname);
              st.setString(2,Lname);
              st.setString(3,Uname);
              st.setString(4,Password);
              st.setString(5,dob1);
              //st.setString(7,Cnumber);
              int i=st.executeUpdate();
              if(i>0){
                JOptionPane.showMessageDialog(this,"Sign-up sucessfully");
              }
              else{
                JOptionPane.showMessageDialog(this,"Failed ");
              }
              
                  
           }catch(Exception e){
               e.printStackTrace();
           }
       }
    
    boolean validation()
    {
    Fname=txtFname.getText();
    Lname=txtLname.getText();
    Uname=txtUname.getText();
    Password=txtPfield.getText();
    CPassword=txtCPfield.getText();
    //Cnumber=txtCnum.getText();
    dob=txtdob.getDate();
    String Cnumber=txtCnum.getText();
    if(Fname.equals(""))
    {
        JOptionPane.showMessageDialog(this, "Please Enter First name ...");
        return false;
    }
    if(Lname.equals(""))
    {
        JOptionPane.showMessageDialog(this, "Please Enter Last name ...");
        return false;
    }
    if(Uname.equals(""))
    {
        JOptionPane.showMessageDialog(this, "Please Enter User name ...");
        return false;
    }
    if(Password.equals(""))
    {
        JOptionPane.showMessageDialog(this, "Please Enter Password ...");
        return false;
    }
    if(CPassword.equals(""))
    {
        JOptionPane.showMessageDialog(this, "Please Enter Confirm Password ...");
        return false;
    }
    if (!Password.equals(CPassword)) 
    { // Check if passwords match
        JOptionPane.showMessageDialog(this, "Passwords do not match.");
        return false;
    }
   
    
    if(dob.equals(null))
    {
        JOptionPane.showMessageDialog(this, "Please Enter DOB ...");
        return false;
    }
    if (Cnumber.equals("") || Cnumber.length() != 10) { // Check contact number length
        JOptionPane.showMessageDialog(this, "Contact number must be exactly 10 digits.");
        return false;
    }
    if (!Cnumber.matches("\\d{10}")) { // Ensure all 10 characters are digits
        JOptionPane.showMessageDialog(this, "Contact number can only contain digits.");
        return false;
    }
    return true;
    }
    
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsignin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel confirmpassworderror;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelcontact;
    private javax.swing.JLabel lablepassworderror;
    private javax.swing.JPasswordField txtCPfield;
    private javax.swing.JTextField txtCnum;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JPasswordField txtPfield;
    private javax.swing.JTextField txtUname;
    private com.toedter.calendar.JDateChooser txtdob;
    // End of variables declaration//GEN-END:variables
}
